---

# Default values
defaults:
    seeing: 0.8 arcsec
    airmass: 1.2
    water_vapor: 1.6 mm

# Directory for atmosphere files, relative or absolute
file_directory: calculator/atmosphere/files

# Pattern to match for transmission/emission files, program matches the start of the filenames against these strings
emission_filepath: mk_skybg_zm_
transmission_filepath: mktrans_zm_

# Indices for transmission/emission files, must correspond to file contents!!
airmass_index: [1.0, 1.5, 2.0]  # All possible values for airmass as shown in file metadata
water_vapor_index: [1 mm, 1.6 mm, 3 mm, 5 mm]  # All possible values for water vapor as shown in file metadata
wavelength_index: [0.31 um, 5.6 um, 0.02 nm]  # min (inclusive), max (exclusive), step size -- from file wavelength values
