---
# NIRES config file
# Want overhead to calculate clock time, where should I get it? -- Sherry is on it, incorporate when available


defaults:
  slit: [0.55 arcsec, 18 arcsec]  # Width, length
  mode: spectroscopic
  wavelength_band: K
  binning: [1, 1]

mode_options: [spectroscopic]

throughput_path: throughput  # Relative path to throughput file directory

exposure_options: [dithers, repeats, coadds, reads]  # Specifies whether or not these parameters should be available for this instrument

spectroscopic:

  pixel_size: 0.0225 arcsec^2/pixel

  dark_current: 0.13 electron / (pixel s)

  read_noise: 15 sqrt(electron/pixel)  # Kind of a nonsense unit, but read noise is actually variance and needs to be squared later...
  # Is this per pixel?? Check w/ Sherry and make sure!

  slit_options: [ [0.55 arcsec, 18 arcsec] ]

  custom_slits: false

  spectral_resolution: 2700  # Spectral resolving power of instrument, defined as λ / Δλ

  filter_options: []

  grating_options: []

  grism_options: []

  dichroic_options: []

  gain: 3.8 electron / adu

  nonlinear_depth: 30000 adu  # Confirm number with Sherry

  # Options for binning [spatial, spectral]
  binning_options: [ [1,1] ]